version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
       - "52001:80"

  nodejs:
    image: fedora/nodejs
    container_name: nodejs
    ports:
       - "52002:8080"
       
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    ports:
     - "52003:8081"
    volumes:
     - ~/artifactory/data:/var/opt/jfrog/artifactory/data
     - ~/artifactory/logs:/var/opt/jfrog/artifactory/logs
     - ~/artifactory/backup:/var/opt/jfrog/artifactory/backup
    restart: always

  jenkins:
    image: jenkins:latest
    container_name: jenkins
    volumes:
     - ~/jenkins/conf:/var/jenkins_home
    ports:
     - "52004:8080"
     - "52005:50000"
    restart: always

  postfix:
    image: catatnight/postfix
    container_name: postfix
    environment:
     - maildomain=localhost
     - smtp_user=postfix:postfix
    ports:
     - "52006:25"     # SMTP
     - "52007:110"   # POP3   STARTTLS

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ~/mysql/configdb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD='mysql'
      - MYSQL_DATABASE='mysql'
      - MYSQL_USER='mysql'
      - MYSQL_PASSWORD='mysql'
    ports:
     - "52008:3306"
    restart: always
    
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes: 
     - ~/mongo/configdb:/data/configdb
    ports:
     - "52009:27017"
     - "52010:28017"
    restart: always

  mongo-ui:
    depends_on:
     - mongo
    image: mongo-express:latest
    container_name: mongo-ui
    ports:
     - "52011:8081" 
     
